### ISSUE TITLE
[polaris] spack chooses openmpi instead of cray-mpich

### ISSUE THREAD

**Issue by mdorier** [mochi-hpc-experiments/platform-configurations#38]
I'm opening this issue to track progress on why spack is picking openmpi instead of cray-mpich when the build cache is enabled.
I had the issue happen even without the build cache. This is I think the solution:

Currently the spack.yaml file has this:

```
  packages:
    all:
      providers:
        mpi: [ cray-mpich ]
        pkgconfig: [ pkg-config ]
      compiler:
      - gcc@12.3
      target:
      - zen3
```

However this format is deprecated. It should be changed to this:

```
packages:
    mpi:
      require:
      - cray-mpich
    pkgconfig:
      require:
      - pkg-config
```

It's not really necessary to specify gcc and zen3, spack will pick them by default. For completeness if we wanted to have them, it would be:

```
  packages:
    all:
      require:
      - "%gcc@12.3"
      - "target=zen3"
    mpi:
      require:
      - cray-mpich
    pkgconfig:
      require:
      - pkg-config
```

This however really forces `gcc 12.3` compiler and `zen3` architecture. The build cache has packages built with other (compatible) versions of gcc and targeting x86_64 architecture, so by having such strong requirements, we will prevent the use of the build cache.

Note: right now some packages still fail to build with the build cache enabled; it seems that there is a conflict between some libraries so versions between the build cache and the platform. I need to look more into this. But at any rate, the above is the correct way of forcing the use of cray-mpich.
